apiVersion: v1
kind: ConfigMap
metadata:
  name: gcp-config
  namespace: default
data:
  DEVICE_ID: aki-raspberry-pi
  GOOGLE_CLOUD_PROJECT: aki-pehkonen
  GOOGLE_CLOUD_TOPIC_ID: projects/aki-pehkonen/topics/raspberry-pi
  GOOGLE_APPLICATION_CREDENTIALS: /etc/config/aki-pehkonen-6bc89aed1f13.json

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-temperature
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k3s-temperature
  template:
    metadata:
      labels:
        app: k3s-temperature
    spec:
      containers:
        - image: ghcr.io/apehkone/raspberrypi-k3s-temperature:latest
          name: k3s-temperature
          securityContext:
            privileged: true
          env:
            - name: DEVICE_ID
              valueFrom:
                configMapKeyRef:
                  name: gcp-config
                  key: DEVICE_ID
            - name: GOOGLE_CLOUD_TOPIC_ID
              valueFrom:
                configMapKeyRef:
                  name: gcp-config
                  key: GOOGLE_CLOUD_TOPIC_ID
            - name: GOOGLE_CLOUD_PROJECT
              valueFrom:
                configMapKeyRef:
                  name: gcp-config
                  key: GOOGLE_CLOUD_PROJECT
            - name: GOOGLE_APPLICATION_CREDENTIALS
              valueFrom:
                configMapKeyRef:
                  name: gcp-config
                  key: GOOGLE_APPLICATION_CREDENTIALS
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: gcp-account
        - name: gcp-config
          configMap:
            name: gcp-config
            items:
            - key: "DEVICE_ID"
              path: "DEVICE_ID"
            - key: "GOOGLE_CLOUD_PROJECT"
              path: "GOOGLE_CLOUD_PROJECT"
            - key: "GOOGLE_CLOUD_TOPIC_ID"
              path: "GOOGLE_CLOUD_TOPIC_ID"
            - key: "GOOGLE_APPLICATION_CREDENTIALS"
              path: "GOOGLE_APPLICATION_CREDENTIALS"